apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xgb-anomaly-classifier-native
  namespace: farah-boubaker-dev
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: xgboost
        version: "1"
      runtime: mlserver-xgboost
      storage:
        key: minio-provisionnement
        path: xgb-anomaly-classifier-native
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"